package com.Anchored.mylife.ui

import com.Anchored.mylife.R

/**
 * 图鉴文案的资源索引。
 *
 * 由 scripts/preset_i18n/generate_preset_i18n.ps1 生成，不要手改。
 * 数组下标 = 图鉴条目 id - [FIRST_ID]，和 assets/preset_achievements.json 里的 id 一一对应。
 *
 * 写成 R.string.xxx 而不是 getIdentifier()：如果 XML 和这里对不上，编译会直接报错。
 */
internal object PresetStringRes {

    private const val FIRST_ID = 1L

    private val TITLE = intArrayOf(
        R.string.preset_1_title,
        R.string.preset_2_title,
        R.string.preset_3_title,
        R.string.preset_4_title,
        R.string.preset_5_title,
        R.string.preset_6_title,
        R.string.preset_7_title,
        R.string.preset_8_title,
        R.string.preset_9_title,
        R.string.preset_10_title,
        R.string.preset_11_title,
        R.string.preset_12_title,
        R.string.preset_13_title,
        R.string.preset_14_title,
        R.string.preset_15_title,
        R.string.preset_16_title,
        R.string.preset_17_title,
        R.string.preset_18_title,
        R.string.preset_19_title,
        R.string.preset_20_title,
        R.string.preset_21_title,
        R.string.preset_22_title,
        R.string.preset_23_title,
        R.string.preset_24_title,
        R.string.preset_25_title,
        R.string.preset_26_title,
        R.string.preset_27_title,
        R.string.preset_28_title,
        R.string.preset_29_title,
        R.string.preset_30_title,
        R.string.preset_31_title,
        R.string.preset_32_title,
        R.string.preset_33_title,
        R.string.preset_34_title,
        R.string.preset_35_title,
        R.string.preset_36_title,
        R.string.preset_37_title,
        R.string.preset_38_title,
        R.string.preset_39_title,
        R.string.preset_40_title,
        R.string.preset_41_title,
        R.string.preset_42_title,
        R.string.preset_43_title,
        R.string.preset_44_title,
        R.string.preset_45_title,
        R.string.preset_46_title,
        R.string.preset_47_title,
        R.string.preset_48_title,
        R.string.preset_49_title,
        R.string.preset_50_title,
        R.string.preset_51_title,
        R.string.preset_52_title,
        R.string.preset_53_title,
        R.string.preset_54_title,
        R.string.preset_55_title,
        R.string.preset_56_title,
        R.string.preset_57_title,
        R.string.preset_58_title,
        R.string.preset_59_title,
        R.string.preset_60_title,
        R.string.preset_61_title,
        R.string.preset_62_title,
        R.string.preset_63_title,
        R.string.preset_64_title,
        R.string.preset_65_title,
        R.string.preset_66_title,
        R.string.preset_67_title,
        R.string.preset_68_title,
        R.string.preset_69_title,
        R.string.preset_70_title,
        R.string.preset_71_title,
        R.string.preset_72_title,
        R.string.preset_73_title,
        R.string.preset_74_title,
        R.string.preset_75_title,
        R.string.preset_76_title,
        R.string.preset_77_title,
        R.string.preset_78_title,
        R.string.preset_79_title,
        R.string.preset_80_title,
        R.string.preset_81_title,
        R.string.preset_82_title,
        R.string.preset_83_title,
        R.string.preset_84_title,
        R.string.preset_85_title,
        R.string.preset_86_title,
        R.string.preset_87_title,
        R.string.preset_88_title,
        R.string.preset_89_title,
        R.string.preset_90_title,
        R.string.preset_91_title,
        R.string.preset_92_title,
        R.string.preset_93_title,
        R.string.preset_94_title,
        R.string.preset_95_title,
        R.string.preset_96_title,
        R.string.preset_97_title,
        R.string.preset_98_title,
        R.string.preset_99_title,
        R.string.preset_100_title,
        R.string.preset_101_title,
        R.string.preset_102_title,
        R.string.preset_103_title,
        R.string.preset_104_title,
        R.string.preset_105_title,
        R.string.preset_106_title,
        R.string.preset_107_title,
        R.string.preset_108_title,
        R.string.preset_109_title,
    )

    private val DESCRIPTION = intArrayOf(
        R.string.preset_1_desc,
        R.string.preset_2_desc,
        R.string.preset_3_desc,
        R.string.preset_4_desc,
        R.string.preset_5_desc,
        R.string.preset_6_desc,
        R.string.preset_7_desc,
        R.string.preset_8_desc,
        R.string.preset_9_desc,
        R.string.preset_10_desc,
        R.string.preset_11_desc,
        R.string.preset_12_desc,
        R.string.preset_13_desc,
        R.string.preset_14_desc,
        R.string.preset_15_desc,
        R.string.preset_16_desc,
        R.string.preset_17_desc,
        R.string.preset_18_desc,
        R.string.preset_19_desc,
        R.string.preset_20_desc,
        R.string.preset_21_desc,
        R.string.preset_22_desc,
        R.string.preset_23_desc,
        R.string.preset_24_desc,
        R.string.preset_25_desc,
        R.string.preset_26_desc,
        R.string.preset_27_desc,
        R.string.preset_28_desc,
        R.string.preset_29_desc,
        R.string.preset_30_desc,
        R.string.preset_31_desc,
        R.string.preset_32_desc,
        R.string.preset_33_desc,
        R.string.preset_34_desc,
        R.string.preset_35_desc,
        R.string.preset_36_desc,
        R.string.preset_37_desc,
        R.string.preset_38_desc,
        R.string.preset_39_desc,
        R.string.preset_40_desc,
        R.string.preset_41_desc,
        R.string.preset_42_desc,
        R.string.preset_43_desc,
        R.string.preset_44_desc,
        R.string.preset_45_desc,
        R.string.preset_46_desc,
        R.string.preset_47_desc,
        R.string.preset_48_desc,
        R.string.preset_49_desc,
        R.string.preset_50_desc,
        R.string.preset_51_desc,
        R.string.preset_52_desc,
        R.string.preset_53_desc,
        R.string.preset_54_desc,
        R.string.preset_55_desc,
        R.string.preset_56_desc,
        R.string.preset_57_desc,
        R.string.preset_58_desc,
        R.string.preset_59_desc,
        R.string.preset_60_desc,
        R.string.preset_61_desc,
        R.string.preset_62_desc,
        R.string.preset_63_desc,
        R.string.preset_64_desc,
        R.string.preset_65_desc,
        R.string.preset_66_desc,
        R.string.preset_67_desc,
        R.string.preset_68_desc,
        R.string.preset_69_desc,
        R.string.preset_70_desc,
        R.string.preset_71_desc,
        R.string.preset_72_desc,
        R.string.preset_73_desc,
        R.string.preset_74_desc,
        R.string.preset_75_desc,
        R.string.preset_76_desc,
        R.string.preset_77_desc,
        R.string.preset_78_desc,
        R.string.preset_79_desc,
        R.string.preset_80_desc,
        R.string.preset_81_desc,
        R.string.preset_82_desc,
        R.string.preset_83_desc,
        R.string.preset_84_desc,
        R.string.preset_85_desc,
        R.string.preset_86_desc,
        R.string.preset_87_desc,
        R.string.preset_88_desc,
        R.string.preset_89_desc,
        R.string.preset_90_desc,
        R.string.preset_91_desc,
        R.string.preset_92_desc,
        R.string.preset_93_desc,
        R.string.preset_94_desc,
        R.string.preset_95_desc,
        R.string.preset_96_desc,
        R.string.preset_97_desc,
        R.string.preset_98_desc,
        R.string.preset_99_desc,
        R.string.preset_100_desc,
        R.string.preset_101_desc,
        R.string.preset_102_desc,
        R.string.preset_103_desc,
        R.string.preset_104_desc,
        R.string.preset_105_desc,
        R.string.preset_106_desc,
        R.string.preset_107_desc,
        R.string.preset_108_desc,
        R.string.preset_109_desc,
    )

    private val STORY = intArrayOf(
        R.string.preset_1_story,
        R.string.preset_2_story,
        R.string.preset_3_story,
        R.string.preset_4_story,
        R.string.preset_5_story,
        R.string.preset_6_story,
        R.string.preset_7_story,
        R.string.preset_8_story,
        R.string.preset_9_story,
        R.string.preset_10_story,
        R.string.preset_11_story,
        R.string.preset_12_story,
        R.string.preset_13_story,
        R.string.preset_14_story,
        R.string.preset_15_story,
        R.string.preset_16_story,
        R.string.preset_17_story,
        R.string.preset_18_story,
        R.string.preset_19_story,
        R.string.preset_20_story,
        R.string.preset_21_story,
        R.string.preset_22_story,
        R.string.preset_23_story,
        R.string.preset_24_story,
        R.string.preset_25_story,
        R.string.preset_26_story,
        R.string.preset_27_story,
        R.string.preset_28_story,
        R.string.preset_29_story,
        R.string.preset_30_story,
        R.string.preset_31_story,
        R.string.preset_32_story,
        R.string.preset_33_story,
        R.string.preset_34_story,
        R.string.preset_35_story,
        R.string.preset_36_story,
        R.string.preset_37_story,
        R.string.preset_38_story,
        R.string.preset_39_story,
        R.string.preset_40_story,
        R.string.preset_41_story,
        R.string.preset_42_story,
        R.string.preset_43_story,
        R.string.preset_44_story,
        R.string.preset_45_story,
        R.string.preset_46_story,
        R.string.preset_47_story,
        R.string.preset_48_story,
        R.string.preset_49_story,
        R.string.preset_50_story,
        R.string.preset_51_story,
        R.string.preset_52_story,
        R.string.preset_53_story,
        R.string.preset_54_story,
        R.string.preset_55_story,
        R.string.preset_56_story,
        R.string.preset_57_story,
        R.string.preset_58_story,
        R.string.preset_59_story,
        R.string.preset_60_story,
        R.string.preset_61_story,
        R.string.preset_62_story,
        R.string.preset_63_story,
        R.string.preset_64_story,
        R.string.preset_65_story,
        R.string.preset_66_story,
        R.string.preset_67_story,
        R.string.preset_68_story,
        R.string.preset_69_story,
        R.string.preset_70_story,
        R.string.preset_71_story,
        R.string.preset_72_story,
        R.string.preset_73_story,
        R.string.preset_74_story,
        R.string.preset_75_story,
        R.string.preset_76_story,
        R.string.preset_77_story,
        R.string.preset_78_story,
        R.string.preset_79_story,
        R.string.preset_80_story,
        R.string.preset_81_story,
        R.string.preset_82_story,
        R.string.preset_83_story,
        R.string.preset_84_story,
        R.string.preset_85_story,
        R.string.preset_86_story,
        R.string.preset_87_story,
        R.string.preset_88_story,
        R.string.preset_89_story,
        R.string.preset_90_story,
        R.string.preset_91_story,
        R.string.preset_92_story,
        R.string.preset_93_story,
        R.string.preset_94_story,
        R.string.preset_95_story,
        R.string.preset_96_story,
        R.string.preset_97_story,
        R.string.preset_98_story,
        R.string.preset_99_story,
        R.string.preset_100_story,
        R.string.preset_101_story,
        R.string.preset_102_story,
        R.string.preset_103_story,
        R.string.preset_104_story,
        R.string.preset_105_story,
        R.string.preset_106_story,
        R.string.preset_107_story,
        R.string.preset_108_story,
        R.string.preset_109_story,
    )

    /** 分类名（数据库里存的中文）-> 资源 id */
    private val CATEGORY = mapOf(
        "成长" to R.string.preset_category_growth,
        "生活" to R.string.preset_category_life,
        "旅行" to R.string.preset_category_travel,
        "学业" to R.string.preset_category_education,
        "情感" to R.string.preset_category_relationships,
        "娱乐" to R.string.preset_category_entertainment,
        "社交" to R.string.preset_category_social,
        "兴趣" to R.string.preset_category_hobbies,
        "技能" to R.string.preset_category_skills,
        "职业" to R.string.preset_category_career,
        "家庭" to R.string.preset_category_family,
        "新手村" to R.string.preset_category_starter_village,
        "健康" to R.string.preset_category_health,
        "财务" to R.string.preset_category_finance,
    )

    fun titleOf(id: Long): Int? = TITLE.getOrNull(indexOf(id))

    fun descriptionOf(id: Long): Int? = DESCRIPTION.getOrNull(indexOf(id))

    fun storyOf(id: Long): Int? = STORY.getOrNull(indexOf(id))

    fun categoryOf(name: String): Int? = CATEGORY[name]

    private fun indexOf(id: Long): Int = (id - FIRST_ID).toInt()
}